#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
make_custom_lang.py — 交互式自定义 cfdialog 语言包

用法:
    python make_custom_lang.py
    python make_custom_lang.py --code de --ref zh_CN    # 非交互
    python make_custom_lang.py --ui en                  # 界面强制英文

流程:
    1) 选择界面语言（中文 / English）
    2) 输入系统语言代码（例如 de、ru、pt_BR）
    3) 输入语言显示名称（本地名）
    4) 选择参考语言（zh_CN / en）
    5) 逐条输入翻译；直接回车 = 保留英语回退
    6) 保存到 lg/<code>.txt

修复记录:
    * _ui(lang, key, **fmt) -> _ui(lang, name, **fmt)
      避免与调用处 key=key 关键字参数冲突。
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List, Optional

THIS_DIR = Path(__file__).resolve().parent

# ---- 尽量从库导入；失败时退化到内置最小集 ----
try:
    sys.path.insert(0, str(THIS_DIR))
    from cfdialog import _BUILTIN_STRINGS, LG_DIR  # type: ignore
except Exception:
    _BUILTIN_STRINGS = {"en": {}, "zh_CN": {}}
    LG_DIR = THIS_DIR / "lg"


# =========================================================================== #
#                          界面文案                                            #
# =========================================================================== #

UI = {
    "en": {
        "title": "─── cfdialog custom language pack maker ───",
        "ui_lang": "Interface language",
        "ui_lang_choice": "Choose 1) 中文  2) English",
        "code": "Language code (e.g. de, ru, pt_BR)",
        "name": "Language display name (native)",
        "name_en": "Language name in English",
        "ref": "Reference language (1=zh_CN, 2=en)",
        "existing": "The file lg/{code}.txt already exists. Overwrite?",
        "start": "Starting interactive translation...",
        "hint": "Press Enter to keep English fallback. Type :q to save and quit.",
        "progress": "[{i}/{total}] {field}",
        "ref_value": "  ref> {value}",
        "prompt": "  new> ",
        "saved": "Saved: {path}",
        "aborted": "Aborted.",
        "invalid_choice": "! Invalid choice.",
        "code_required": "! Language code cannot be empty.",
        "done": "Done. Language pack written to {path}.",
        "summary": "Filled {n} key(s). Others keep English fallback.",
    },
    "zh_CN": {
        "title": "─── cfdialog 自定义语言包制作工具 ───",
        "ui_lang": "界面语言",
        "ui_lang_choice": "请选择 1) 中文  2) English",
        "code": "系统语言代码（例如 de、ru、pt_BR）",
        "name": "语言显示名称（本地语言书写）",
        "name_en": "语言的英文名称",
        "ref": "参考语言（1=zh_CN，2=en）",
        "existing": "文件 lg/{code}.txt 已存在，是否覆盖？",
        "start": "开始交互式翻译...",
        "hint": "直接回车 = 保留英语回退。输入 :q 保存并退出。",
        "progress": "[{i}/{total}] {field}",
        "ref_value": "  参考> {value}",
        "prompt": "  新建> ",
        "saved": "已保存: {path}",
        "aborted": "已取消。",
        "invalid_choice": "! 无效选择。",
        "code_required": "! 语言代码不能为空。",
        "done": "完成。语言包已写入 {path}。",
        "summary": "已填写 {n} 项，其余保留英语回退。",
    },
}


def _ui(lang: str, name: str, **fmt) -> str:
    """取界面文案。第二个参数刻意不叫 key，避免与 key=... 冲突。"""
    table = UI.get(lang) or UI["en"]
    s = table.get(name, UI["en"].get(name, name))
    if fmt:
        try:
            return s.format(**fmt)
        except Exception:
            return s
    return s


# =========================================================================== #
#                          输入辅助                                            #
# =========================================================================== #

def _ask(prompt: str, default: str = "") -> str:
    hint = f" [{default}]" if default else ""
    try:
        return input(f"{prompt}{hint}\n> ").strip() or default
    except EOFError:
        return default


def _ask_yesno(prompt: str, default: str = "n") -> bool:
    raw = _ask(prompt, default).lower()
    return raw in ("y", "yes", "是", "1", "true")


def _choose_ui_lang() -> str:
    print(_ui("zh_CN", "title"))
    print()
    print(_ui("zh_CN", "ui_lang"))
    raw = _ask(_ui("zh_CN", "ui_lang_choice"), "1")
    return "zh_CN" if raw in ("1", "zh", "zh_CN", "中文", "") else "en"


# =========================================================================== #
#                          写入文件                                            #
# =========================================================================== #

def _write_pack(code: str, meta: dict, strings: dict) -> Path:
    LG_DIR.mkdir(parents=True, exist_ok=True)
    path = LG_DIR / f"{code}.txt"
    lines: List[str] = []
    lines.append("# cfdialog custom language pack")
    lines.append(f"# code={meta.get('code', code)}")
    lines.append(f"# name={meta.get('name', code)}")
    lines.append(f"# name_en={meta.get('name_en', code)}")
    lines.append(f"# native_name={meta.get('native_name', code)}")
    lines.append("#")
    lines.append("# Generated by make_custom_lang.py")
    lines.append("")
    for k, v in strings.items():
        if v is None:
            continue
        lines.append(f"{k}={v}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


# =========================================================================== #
#                          主流程                                              #
# =========================================================================== #

def run_interactive(ui_lang: str,
                    code: Optional[str] = None,
                    name: Optional[str] = None,
                    name_en: Optional[str] = None,
                    ref: Optional[str] = None) -> int:
    # ---- 采集元数据 ----
    while not code:
        code = _ask(_ui(ui_lang, "code"))
        if not code:
            print(_ui(ui_lang, "code_required"))

    if not name:
        name = _ask(_ui(ui_lang, "name"), code)
    if not name_en:
        name_en = _ask(_ui(ui_lang, "name_en"), name or code)

    if ref is None:
        r = _ask(_ui(ui_lang, "ref"), "2")
        ref = "zh_CN" if r in ("1", "zh_CN", "zh") else "en"

    ref_table = _BUILTIN_STRINGS.get(ref) or _BUILTIN_STRINGS.get("en") or {}
    if not ref_table:
        print("! Reference language table unavailable; using empty key list.")
        return 1

    path = LG_DIR / f"{code}.txt"
    if path.exists():
        if not _ask_yesno(_ui(ui_lang, "existing", code=code), "n"):
            print(_ui(ui_lang, "aborted"))
            return 1

    # ---- 逐条翻译 ----
    print()
    print(_ui(ui_lang, "start"))
    print(_ui(ui_lang, "hint"))
    print()

    keys = list(ref_table.keys())
    total = len(keys)
    result: dict = {}

    for i, field in enumerate(keys, 1):
        ref_val = ref_table.get(field, "")
        # 注意：这里用 field= 传值，不再用 key=
        print(_ui(ui_lang, "progress", i=i, total=total, field=field))
        if ref_val:
            print(_ui(ui_lang, "ref_value", value=ref_val))
        try:
            new_val = input(_ui(ui_lang, "prompt"))
        except EOFError:
            new_val = ""
        new_val = new_val.rstrip("\n")

        if new_val == ":q":
            print(_ui(ui_lang, "aborted"))
            break
        if new_val == "":
            continue
        result[field] = new_val

    meta = {
        "code": code,
        "name": name or code,
        "name_en": name_en or name or code,
        "native_name": name or code,
    }
    final_path = _write_pack(code, meta, result)
    print()
    print(_ui(ui_lang, "summary", n=len(result)))
    print(_ui(ui_lang, "done", path=final_path))
    return 0


# =========================================================================== #
#                          入口                                                #
# =========================================================================== #

def main(argv: List[str] = None) -> int:
    parser = argparse.ArgumentParser(
        description="cfdialog custom language pack maker"
    )
    parser.add_argument("--code", default=None,
                        help="Language code, e.g. de")
    parser.add_argument("--name", default=None,
                        help="Language display name (native)")
    parser.add_argument("--name-en", dest="name_en", default=None,
                        help="English name of the language")
    parser.add_argument("--ref", default=None, choices=("zh_CN", "en"),
                        help="Reference language")
    parser.add_argument("--ui", default=None, choices=("zh_CN", "en"),
                        help="Interface language")
    args = parser.parse_args(argv)

    ui_lang = args.ui or _choose_ui_lang()
    return run_interactive(
        ui_lang,
        code=args.code,
        name=args.name,
        name_en=args.name_en,
        ref=args.ref,
    )


if __name__ == "__main__":
    raise SystemExit(main())